# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('location', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Internship', 'Internship')], max_length=25)),
                ('add_timestamp', models.DateTimeField()),
            ],
        ),
    ]
