# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 05:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_shirt', models.BooleanField(verbose_name=b'Wearing ACM Shirt')),
                ('points', models.IntegerField(default=1, verbose_name=b'Points')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name=b'Name')),
                ('sequence', models.IntegerField(unique=True, verbose_name=b'Sequence')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Active')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_dues', models.BooleanField(default=False, verbose_name=b'Paid Dues')),
                ('received_shirt', models.BooleanField(default=False, verbose_name=b'Received Shirt')),
            ],
            options={
                'ordering': ['semester', 'member'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'Name')),
                ('datetime', models.DateTimeField(verbose_name=b'Date/time')),
                ('attendance_start', models.DateTimeField(blank=True, null=True, verbose_name=b'Attendance Start')),
                ('attendance_end', models.DateTimeField(blank=True, null=True, verbose_name=b'Attendance End')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Password')),
            ],
            options={
                'ordering': ['datetime'],
                'get_latest_by': 'datetime',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoj_username', models.CharField(blank=True, max_length=80, verbose_name=b'SPOJ Username')),
                ('is_byu', models.BooleanField(default=True, verbose_name=b'Is BYU Student')),
                ('is_cs', models.BooleanField(default=True, verbose_name=b'Is CS Student')),
                ('is_undergraduate', models.BooleanField(default=True, verbose_name=b'Is Undergraduate')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Website')),
                ('attendances', models.ManyToManyField(blank=True, null=True, through='membership.Attendance', to='membership.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name=b'Name')),
                ('enrollment_start', models.DateTimeField(verbose_name=b'Enrollment Start')),
                ('enrollment_end', models.DateTimeField(verbose_name=b'Enrollment End')),
            ],
            options={
                'ordering': ['enrollment_start', 'enrollment_end'],
                'get_latest_by': 'enrollment_start',
            },
        ),
        migrations.CreateModel(
            name='ShirtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr_name', models.CharField(max_length=4, verbose_name=b'Abbreviated Name')),
                ('full_name', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'Full Name')),
                ('sequence', models.IntegerField(unique=True, verbose_name=b'Sequence')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Active')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='membership.Semester', verbose_name=b'Graduating'),
        ),
        migrations.AddField(
            model_name='member',
            name='highest_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Course', verbose_name=b'Highest CS Course'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberships',
            field=models.ManyToManyField(blank=True, null=True, through='membership.Enrollment', to='membership.Semester'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Semester', verbose_name=b'Semester'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member', verbose_name=b'Member'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Semester', verbose_name=b'Semester'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.ShirtSize', verbose_name=b'Shirt Size'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Meeting', verbose_name=b'Meeting'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member', verbose_name=b'Member'),
        ),
    ]
