# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='has_shirt',
            field=models.BooleanField(verbose_name='Wearing ACM Shirt'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Meeting', verbose_name='Meeting'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sequence',
            field=models.IntegerField(unique=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member', verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='paid_dues',
            field=models.BooleanField(default=False, verbose_name='Paid Dues'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='received_shirt',
            field=models.BooleanField(default=False, verbose_name='Received Shirt'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.ShirtSize', verbose_name='Shirt Size'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendance_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance End'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendance_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Attendance Start'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(verbose_name='Date/time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='member',
            name='attendances',
            field=models.ManyToManyField(blank=True, through='membership.Attendance', to='membership.Meeting'),
        ),
        migrations.AlterField(
            model_name='member',
            name='graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduation', to='membership.Semester', verbose_name='Graduating'),
        ),
        migrations.AlterField(
            model_name='member',
            name='highest_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membership.Course', verbose_name='Highest CS Course'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_byu',
            field=models.BooleanField(default=True, verbose_name='Is BYU Student'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_cs',
            field=models.BooleanField(default=True, verbose_name='Is CS Student'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_undergraduate',
            field=models.BooleanField(default=True, verbose_name='Is Undergraduate'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberships',
            field=models.ManyToManyField(blank=True, through='membership.Enrollment', to='membership.Semester'),
        ),
        migrations.AlterField(
            model_name='member',
            name='spoj_username',
            field=models.CharField(blank=True, max_length=80, verbose_name='SPOJ Username'),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='enrollment_end',
            field=models.DateTimeField(verbose_name='Enrollment End'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='enrollment_start',
            field=models.DateTimeField(verbose_name='Enrollment Start'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=12, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shirtsize',
            name='abbr_name',
            field=models.CharField(max_length=4, verbose_name='Abbreviated Name'),
        ),
        migrations.AlterField(
            model_name='shirtsize',
            name='full_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='shirtsize',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='shirtsize',
            name='sequence',
            field=models.IntegerField(unique=True, verbose_name='Sequence'),
        ),
    ]
